# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Dec 29 13:22:05 2011
#      by: pyside-uic 0.2.13 running on PySide 1.0.9
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.view = QtWidgets.QTreeView(self.centralwidget)
        self.view.setAlternatingRowColors(True)
        self.view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.view.setAnimated(False)
        self.view.setAllColumnsShowFocus(True)
        self.view.setObjectName("view")
        self.vboxlayout.addWidget(self.view)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 31))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.actionsMenu = QtWidgets.QMenu(self.menubar)
        self.actionsMenu.setObjectName("actionsMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.insertRowAction = QtWidgets.QAction(MainWindow)
        self.insertRowAction.setObjectName("insertRowAction")
        self.removeRowAction = QtWidgets.QAction(MainWindow)
        self.removeRowAction.setObjectName("removeRowAction")
        self.insertColumnAction = QtWidgets.QAction(MainWindow)
        self.insertColumnAction.setObjectName("insertColumnAction")
        self.removeColumnAction = QtWidgets.QAction(MainWindow)
        self.removeColumnAction.setObjectName("removeColumnAction")
        self.insertChildAction = QtWidgets.QAction(MainWindow)
        self.insertChildAction.setObjectName("insertChildAction")
        self.fileMenu.addAction(self.exitAction)
        self.actionsMenu.addAction(self.insertRowAction)
        self.actionsMenu.addAction(self.insertColumnAction)
        self.actionsMenu.addSeparator()
        self.actionsMenu.addAction(self.removeRowAction)
        self.actionsMenu.addAction(self.removeColumnAction)
        self.actionsMenu.addSeparator()
        self.actionsMenu.addAction(self.insertChildAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.actionsMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Editable Tree Model", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.fileMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.actionsMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Actions", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.exitAction.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.exitAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.insertRowAction.setText(QtWidgets.QApplication.translate("MainWindow", "Insert Row", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.insertRowAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I, R", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.removeRowAction.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Row", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.removeRowAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R, R", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.insertColumnAction.setText(QtWidgets.QApplication.translate("MainWindow", "Insert Column", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.insertColumnAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I, C", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.removeColumnAction.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Column", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.removeColumnAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R, C", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.insertChildAction.setText(QtWidgets.QApplication.translate("MainWindow", "Insert Child", None, QtWidgets.QApplication.UnicodeUTF8))
        # self.insertChildAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, QtWidgets.QApplication.UnicodeUTF8))

        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Editable Tree Model", None))
        self.fileMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None ))
        self.actionsMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Actions", None ))
        self.exitAction.setText(QtWidgets.QApplication.translate("MainWindow", "E&xit", None ))
        self.exitAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None ))
        self.insertRowAction.setText(QtWidgets.QApplication.translate("MainWindow", "Insert Row", None ))
        self.insertRowAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I, R", None ))
        self.removeRowAction.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Row", None ))
        self.removeRowAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R, R", None ))
        self.insertColumnAction.setText(QtWidgets.QApplication.translate("MainWindow", "Insert Column", None ))
        self.insertColumnAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I, C", None ))
        self.removeColumnAction.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Column", None ))
        self.removeColumnAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R, C", None ))
        self.insertChildAction.setText(QtWidgets.QApplication.translate("MainWindow", "Insert Child", None ))
        self.insertChildAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None ))
